version: '3'
services:
  waitfordb:
    image: dadarek/wait-for-dependencies
    depends_on:
      - postgresql
    command: postgresql:5432

  postgresql:
    image: postgres:10.5
    container_name: postgresql
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: mlflow-db
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    hostname: postgresql
    restart: always

  mlflow:
    build: ./mlflow
    container_name: mlflow
    ports:
      - 5000:5000
    depends_on:
      - postgresql
      - waitfordb
    volumes:
      - ./artifacts:/tmp/artifacts
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      VIRTUAL_HOST: mlflow-server
      VIRTUAL_PORT: 5000
      ARTIFACT_PATH: /tmp/artifacts
  
  evalapp:
    build: ./evalapp
    container_name: evalapp
    ports:
      - 8000:8000
    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5000/
      COMPETITION_NAME: first-competition
    depends_on:
      - mlflow